

siamese_config = {
	'EMBEDDING_DIM': 100,
	'MAX_SEQUENCE_LENGTH' : 20,
	'VALIDATION_SPLIT': 0.15,
	'RATE_DROP_LSTM': 0.10,
	'RATE_DROP_DENSE': 0.10,
	'NUMBER_LSTM': 100,
	'NUMBER_DENSE_UNITS': 100,
	'ACTIVATION_FUNCTION': 'relu'
}
